// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmDNOKm3N6MlOZ__-g468ErRpVMuea0Y',
    appId: '1:638138242347:web:5843bb53358941713ce16e',
    messagingSenderId: '638138242347',
    projectId: 'verifikasi-email-7bbb9',
    authDomain: 'verifikasi-email-7bbb9.firebaseapp.com',
    storageBucket: 'verifikasi-email-7bbb9.firebasestorage.app',
    measurementId: 'G-YKSZ2XBVNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSCaNX7IZ36ienGKVy_6f_1WgBo6ovR4',
    appId: '1:638138242347:android:b1a818b6e7bff12c3ce16e',
    messagingSenderId: '638138242347',
    projectId: 'verifikasi-email-7bbb9',
    storageBucket: 'verifikasi-email-7bbb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFXAA-1wzo0PbKMpMdFixM1DDUkKihIqE',
    appId: '1:638138242347:ios:9220dbd1ad389ab03ce16e',
    messagingSenderId: '638138242347',
    projectId: 'verifikasi-email-7bbb9',
    storageBucket: 'verifikasi-email-7bbb9.firebasestorage.app',
    iosClientId: '638138242347-1mnp84jad2fl1h3pveepo442qkapqo15.apps.googleusercontent.com',
    iosBundleId: 'com.example.skenain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFXAA-1wzo0PbKMpMdFixM1DDUkKihIqE',
    appId: '1:638138242347:ios:9220dbd1ad389ab03ce16e',
    messagingSenderId: '638138242347',
    projectId: 'verifikasi-email-7bbb9',
    storageBucket: 'verifikasi-email-7bbb9.firebasestorage.app',
    iosClientId: '638138242347-1mnp84jad2fl1h3pveepo442qkapqo15.apps.googleusercontent.com',
    iosBundleId: 'com.example.skenain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKmDNOKm3N6MlOZ__-g468ErRpVMuea0Y',
    appId: '1:638138242347:web:5746adecf399024b3ce16e',
    messagingSenderId: '638138242347',
    projectId: 'verifikasi-email-7bbb9',
    authDomain: 'verifikasi-email-7bbb9.firebaseapp.com',
    storageBucket: 'verifikasi-email-7bbb9.firebasestorage.app',
    measurementId: 'G-3DZY79G119',
  );
}
